### ISSUE TITLE
mark or report face(s) position?

### ISSUE THREAD

**Issue by dmd** [pi-null-mezon/alignfacehttp#2]
I'm doing a project where I have hundreds of photos of my kids (taken once a week in a standard location), and I'm using alignfacehttp to do the final tweak of lining things up.

I have an issue where in some of them it is finding multiple faces. In a few of those it's obvious what the problem is (like some art on the wall behind them) but in others I don't know.

Is it possible to have the software either draw a box or at the very least *report* the bounding boxes it is finding each face in? Then I could blur or otherwise redact the offending areas so the software won't choke on it.

**Comment by pi-null-mezon** [comment]
This kind of detector behavior is called false positive detection. This project use [dlib](http://dlib.net/)'s HOG face detector and it is outdated / obsolete compare to today's CNN-based detectors. And sorry, but I have no plans to update.

Of course you can return all detected boxes for all faces on photo - fell free to modify `httpsrv.py`.

**Comment by dmd** [comment]
Thanks - I found something that'll help me.

```python
import sys

import dlib

detector = dlib.get_frontal_face_detector()
win = dlib.image_window()

for f in sys.argv[1:]:
    print("Processing file: {}".format(f))
    img = dlib.load_rgb_image(f)
    img = dlib.resize_image(img=img, scale=.3)  #too big to fit on screen
    dets = detector(img, 1)
    print("Number of faces detected: {}".format(len(dets)))
    for i, d in enumerate(dets):
        print("Detection {}: Left: {} Top: {} Right: {} Bottom: {}".format(
            i, d.left(), d.top(), d.right(), d.bottom()))

    win.clear_overlay()
    win.set_image(img)
    win.add_overlay(dets)
    dlib.hit_enter_to_continue()
```

**Comment by dmd** [comment]
(And in the future I'll make sure the kids are in front of something blank!)

**Comment by dmd** [comment]
Oh, I have an even better idea. I should just select the LARGEST face. All my false positives are tiny blurs.
